package com.game.world;

public enum FixtureType {
    DEATH, ITEM, HEAD, FEET, LEFT, RIGHT, BLOCK, LADDER, SHIELD, DAMAGEABLE, DAMAGER, HITTER, FEET_STICKER,
    FORCE, FORCE_LISTENER, GRAVITY_SHIFT, WALL_SLIDE_SENSOR, BOUNCER, BOUNCEABLE, LASER, SCANNER, CUSTOM
}
