package com.game.world;

public enum FixtureType {
    DEATH, ITEM, HEAD, FEET, LEFT, RIGHT, BLOCK, LADDER, SHIELD, DAMAGEABLE, DAMAGER, HITTER_BOX, FEET_STICKER,
    GRAVITY_SHIFT, WALL_SLIDE_SENSOR, BOUNCER, BOUNCEABLE, LASER, CUSTOM
}
