package com.game.constants;

public enum Events {
    PLAYER_DEAD, LEVEL_PAUSED, LEVEL_UNPAUSED, LEVEL_FINISHED, SOUND_VOLUME_CHANGE, TOUCH_GATE, GATE_INIT_OPENING,
    GATE_FINISH_OPENING, GATE_INIT_CLOSING, GATE_FINISH_CLOSING
}
