package com.game.events;

public enum EventType {
    PLAYER_SPAWN, PLAYER_DEAD, LEVEL_PAUSED, LEVEL_UNPAUSED, LEVEL_FINISHED, SOUND_VOLUME_CHANGE, BEGIN_GAME_ROOM_TRANS,
    CONTINUE_GAME_ROOM_TRANS, END_GAME_ROOM_TRANS, TOUCH_GATE, GATE_INIT_OPENING, GATE_FINISH_OPENING,
    GATE_INIT_CLOSING, GATE_FINISH_CLOSING
}
